apiVersion: v1
kind: Service
metadata:
  name: resume-builder-backend-api-svc
  namespace: plasma-namespace
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app-name: resume-builder-backend-api
